name: GitHub Security Report Action
description: Generates security reports for a GitHub repository
author: Jamie Jones
runs:
  using: node12
  main: dist/index.js

branding:
  icon: shield
  color: green